module LexerInAction

// in this chapter we will cover the following
//   1. how to use the Lexer that are generated by the fslex.exe 


(*

as a prerequisite to the rule, you will need to first create the fsyacc.exe

fsyacc.exe Fsyacc.fsy --module Strangelights.ExpressionParser.Parser

and you have to put the generated "Fsyacc.fs" file before the "Fslex.fs" file 


*)

open System.Text
open Microsoft.FSharp.Text.Lexing

(*

REMEMBER to import the generated lexer
*)
open Strangelights.ExpressionParser

let lexbuf = LexBuffer<byte>.FromBytes(Encoding.ASCII.GetBytes("1"))
let token = Lexer.token lexbuf // you will need to open the (* open Strangelights.ExpressionParser *)
printfn "%A" token

printfn "done"

(*

output is as follow 

FLOAT 1.0

*)
