//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://strangelights.com/FSharp/Foundations/WCFServices", ConfigurationName="IGreetingService")]
public interface IGreetingService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://strangelights.com/FSharp/Foundations/WCFServices/IGreetingService/Greet", ReplyAction="http://strangelights.com/FSharp/Foundations/WCFServices/IGreetingService/GreetRes" +
        "ponse")]
    string Greet(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGreetingServiceChannel : IGreetingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GreetingServiceClient : System.ServiceModel.ClientBase<IGreetingService>, IGreetingService
{
    
    public GreetingServiceClient()
    {
    }
    
    public GreetingServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GreetingServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GreetingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GreetingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Greet(string name)
    {
        return base.Channel.Greet(name);
    }
}
